## TIC TAC TOE GAME USING PYTHON 

## Himasnhu Patel 
###  python project (TIC TAC TOE GAME)

In [108]:

import numpy as np

def empty_places(board):
    l = []
    for i in range(len(board)):
        for j in range(len(board[i])):
            if board[i][j] == 0:
                l.append((i, j))
    return l  # Corrected to return the list of empty places

board = np.array([
                  [1, 2, 1],
                  [0, 0, 0],
                  [1, 1, 2]
                ])
print(empty_places(board))


[(1, 0), (1, 1), (1, 2)]


In [109]:
# importting required librries
import numpy as np
import random 
from time import sleep

#creating an empty TIC TAC TOE board
def empty_board():
    board = np.array([
                      [0,0,0],
                      [0,0,0],
                      [0,0,0]
                    ])
    return (board)
    
print(empty_board())

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [110]:
##2 check for empty places on the TIC TAC TOE board
def empty_places(board):
    l = []
    for i in range(len(board)):
        for j in range(len(board[i])):
            if board[i][j] == 0:
                l.append((i, j))
    return l  # Corrected to return the list of empty places

board = np.array([
                  [1, 2, 1],
                  [0, 0, 0],
                  [1, 1, 2]
                ])
print(empty_places(board))


[(1, 0), (1, 1), (1, 2)]


In [111]:
# select a random place for the player on the TIC TAC TOE board
def random_place(board,player):
    select = empty_places(board)
    current_location = random.choice(select)
    board[current_location ]=player
    return(board)
print(random_place(board,1))

[[1 2 1]
 [0 0 1]
 [1 1 2]]


In [112]:
##3 Evaluate for a winner or a TIE

#check the horizonatal rows for a winner
def row_winner(board,player):
    for x in range(len(board)):
        win = True

        for y in range(len(board)):
            if board[x,y] !=player:
                win = False
                break
            
        if win:
            return True
        
    return False
# Example board with a winning row for player 1
board = np.array([
                  [0,0,0],
                  [0,0,0],
                  [1,1,1]
                 
])
print(row_winner(board, 1))


True


In [113]:
# Checks whether the player has three of their marks in a vertical row
def col_winner(board,player):
    for x in range(len(board)):
        win = True

        for y in range(len(board)):
            if board[y,x] !=player:
                win = False
                break
            
        if win:
            return True
        
    return False
# Example board with a winning vertical for player 1
board = np.array([
                  [1,0,0],
                  [1,0,0],
                  [1,0,0]
                 
])
print(col_winner(board, 1))


True


In [114]:
import numpy as np

# Check the diagonal rows for a winner
def diagonal_winner(board, player):
    # Check the first diagonal (top-left to bottom-right)
    win = True
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
            break   

    if win:  
        return True

    # Check the second diagonal (top-right to bottom-left)
    win = True
    for x in range(len(board)):
        y = len(board) - 1 - x
        if board[x, y] != player:
            win = False
            break   
    return win  

# Example board
board = np.array([
                  [0, 0, 1],
                  [0, 1, 0],
                  [1, 0, 0]
])

print(diagonal_winner(board, 1))  # Expected output: True (because the second diagonal matches)


True


In [115]:
##4 Evaluates Whether there is a winner or a Tie
def evaluate_game(board):
    # winneer[0=ongoing game,1 = Player1, 2 = Player2, -1 = TIe]
    winner = 0
    for player in [1,2]:
        if (row_winner(board,player) or
            col_winner(board,player) or
            diagonal_winner(board,player)):

            winner = player
    if np.all(board !=0) and winner == 0:
        winner = -1
    return winner

In [116]:
##5 Main function to run/start the game
def tic_tac_toe():
    board   = empty_board()
    winner  = 0
    counter = 1
    print(board)
    sleep(2)

    while winner == 0:
        for player in[1,2]:
            board = random_place(board,player)
            print("Board after" + str(counter) + "move(2):")
            print(board)
            sleep(2)
            counter+=1
            winner = evaluate_game(board)
            if winner !=0:
                break
    return(winner)
print("winner is player :" + str(tic_tac_toe()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after1move(2):
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Board after2move(2):
[[1 0 0]
 [0 2 0]
 [0 0 0]]
Board after3move(2):
[[1 0 1]
 [0 2 0]
 [0 0 0]]
Board after4move(2):
[[1 0 1]
 [0 2 0]
 [2 0 0]]
Board after5move(2):
[[1 0 1]
 [0 2 0]
 [2 0 1]]
Board after6move(2):
[[1 0 1]
 [2 2 0]
 [2 0 1]]
Board after7move(2):
[[1 0 1]
 [2 2 1]
 [2 0 1]]
winner is player :1
